### PR TITLE
Setup.py

### PR DESCRIPTION
**Pull request by kstola2**
Issue #256 

Run `sudo python3 setup.py install` in the project root directory. It should create a couple new folders and a metadata file. It should also check to install the `ecdsa` and `requests` modules. I'm not sure if we want to redirect the output but regardless we may need torestructure the project again this time more to the likeness of a package.

Let me know if there are any problems running it.

### CODE REVIEW

**Comment by kstola2** [comment]
That's a great question I'm not sure.

**Comment by jldistefano** [comment]
I uninstalled pyqt5 and ran the gui, for some reason it still opens. But a lot of elements are miscolored for some reason. So I think it would probably be a good idea to add pyqt5 to the list of required installs. The module is called `pyqt5`

**Comment by kstola2** [comment]
Okay can you make it the requested change

**Comment by kstola2** [comment]
Alright I added pyqt5

**Pull request merged**
