### PR TITLE
Added transaction pages

### PR DESCRIPTION
**Pull request by jldistefano**
Issue #261

### CODE REVIEW

**Comment by jldistefano** [comment]
Yes, but would you then be ok with the send/copy buttons and
sender/recipient fields to the top?

**Comment by jldistefano** [comment]
I updated the branch. The scroll buttons are now toward bottom of the tab widget and the space between the tabs are increased. Though I'm not quite sure what you mean by columns. If you believe that its difficult to tell which window is currently selected, I could add a label in the tab widget saying "SENT TRANSACTIONS" or "RECEIVED TRANSACTIONS" to specify.

**Comment by jldistefano** [comment]
I've adjusted the transaction window as asked

**Comment by kstola2** [comment]
Is it possible to shift the `Sent` and `Received` to the right a bit? To center it?

**Comment by jldistefano** [comment]
Sure, it should be updated.

**Comment by kstola2** [comment]
Cool

**Pull request merged**
